spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    url: jdbc:postgresql://postgresql:5432
  data:
    redis:
      password: ${DB_PASSWORD}
      ssl:
        enabled: true
  cache:
    redis:
      time-to-live: 5m
      cache-null-values: false
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true